#!/bin/bash

BACLIGHT_DIR='/sys/class/backlight/amdgpu_bl0'
MAX_BRIGHNTESS=`cat $BACLIGHT_DIR/max_brightness`
BRIGHTNESS_FILE="$BACLIGHT_DIR/brightness"

up() {
    current=`get`
    change=`echo "scale=0; $1 * $MAX_BRIGHNTESS / 100" | bc -l`
    value=`echo $current + $change | bc -l`
    set_brightness $value
}

down() {
    current=`get`
    change=`echo "scale=0; $1 * $MAX_BRIGHNTESS / 100" | bc -l`
    value=`echo $current - $change | bc -l`
    set_brightness $value
}


get() {
    cat $BRIGHTNESS_FILE
}

get_percentage() {
    current=`get`
    echo `echo "scale=0; $current * 100 / $MAX_BRIGHNTESS" | bc -l`
}

set_percentage() {
    value=`echo "scale=0; $1 * $MAX_BRIGHNTESS / 100" | bc -l`
    set_brightness $value
}


icon() {
    echo "󰃠"
}

set_brightness() {
    if [ $1 -gt $MAX_BRIGHNTESS ]; then
        exit
    elif [ $1 -lt 0 ]; then
        exit
    fi
    echo $1 > $BRIGHTNESS_FILE
}


[ "$1" = "get" ] && get && exit
[ "$1" = "get-percentage" ] && get_percentage && exit
[ "$1" = "set" ] && set_brightness $2 && exit
[ "$1" = "set-percentage" ] && set_percentage $2 && exit
[ "$1" = "up" ] && up $2 && exit
[ "$1" = "down" ] && down $2 && exit
[ "$1" = "icon" ] && icon && exit
